from .afficher_file_dattente_detail_view import AfficherFileDattenteDetailView
from .afficher_file_dattente_view import AfficherFileDattenteView
from .afficher_file_dattente_pro_view import AfficherFilesDattenteParProfessionnelView
from .afficher_liste_files_dattente_view import AfficherListeFileDattenteView
from .afficher_detail_file_dattente_client_view import AfficherDetailFileAttenteClientView
