from .contacte_serializer import ContacteAdminSerializer, ContactePublicSerializer
from .partenaire_serializer import PartenaireAdminSerializer, PartenairePublicSerializer
from .aboutNous_serializer import AboutNousAdminSerializer, AboutNousPublicSerializer
from .politique_confidentialite_serializer import PolitiqueConfidentialiteAdminSerializer, PolitiqueConfidentialitePublicSerializer
from .condition_dutilisation_serializer import ConditionDutilisationAdminSerializer, ConditionDutilisationPublicSerializer
from .admin_table_serializer import AdminAccountAfficherSerializer, AdminAccountModifierSerializer, AdminAccountModifierPasswordSerializer
from .categorie_serializer import CategorieAfficherSerializer, CategorieSerializer
from .professionnel_serializer import ProfessionnelSerializer
from .client_serializer import AfficherClientSerializer
from .service_serializer import ServiceSerializer, ServiceDetailSerializer, ServicePlanningSerializer, ServicePlanningPauseSerializer, ServicePlanningExceptionSerializer
from .file_dattente_serializer import FileDattenteSerializer, FileDattenteDetailSerializer
from .rdv_serializer import RDVSerializer, CreateRDVSerializer, AfficherListReservationSerializer, AfficherReservationDetailRDVSerializer
from .statistiques_serializer import RDVStatsServiceSerializer, RDVStatsParDateGlobalSerializer, HeureStatsSerializer, RDVStatsParHeureSerializer, RDVStatsParMoisSerializer, ErrorSerializer, RDVStatsParJourResponseSerializer, RDVParStatutSerializer, FileDattenteStatistiquesSerializer, FileDattenteStatsParAnneeSerializer, FileDattenteStatsParDateSerializer, FileDattenteStatsParHeureSerializer, NombreTotalServicesSerializer, NombreTotalCategoriesSerializer, NombreProfessionnelsParCategorieSerializer, NombreClientsSerializer, NombreTotalProfessionnelsSerializer, NombreProfessionnelsActifsSerializer, NombreProfessionnelsSupprimesSerializer, NombreProfessionnelsSuspendusSerializer, NombreServicesParCategorieSerializer, NombreTotalRDVSerializer, NombreServicesParProfessionnelSerializer, RDVNombreAbsentSerializer, RDVNombreAbsentParServiceSerializer, RDVParModeSerializer, RDVParSourceSerializer, RDVStatsParAnneeSerializer, RDVStatsParDateGlobalSerializer, RDVStatsParIntervalleSerializer, RDVNombrePresentSerializer, RDVNombrePresentParServiceSerializer
from .afficher_planning_mois_serializer import AfficherPlanningMoisSerializer
from .afficher_planning_creneaux_serializer import AfficherCreneauxSerializer