from .ajouter_service_view import AjouterServiceView
from .modifier_service_view import ModifierServiceView
from .supprimer_service_view import SupprimerServiceView
from .afficher_service_view import AfficherServiceView
from .afficher_service_detail_view import AfficherServiceDetailView
