# Generated by Django 5.2 on 2026-06-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminToorrii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='niveau',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='adminToorrii.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='couleur_theme',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
