# Generated by Django 5.2 on 2026-08-02 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminToorrii', '0002_categorie_niveau_categorie_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionnelLead',
            fields=[
                ('lead_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('adresse', models.TextField(blank=True, default='')),
                ('wilaya', models.CharField(default='Oran', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non_contacte', 'Non contacté'), ('contacte', 'Contacté'), ('interesse', 'Intéressé'), ('inscrit', 'Inscrit sur Toorrii'), ('refuse', 'Refusé')], default='non_contacte', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='google_places', max_length=50)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='adminToorrii.categorie')),
                ('professionnel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origine', to='adminToorrii.professionnel')),
            ],
            options={
                'verbose_name': 'Lead Professionnel',
                'verbose_name_plural': 'Leads Professionnels',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
