# Generated by Django 5.2 on 2026-08-03 14:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminToorrii', '0003_add_professionnel_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='etat_compte',
            field=models.CharField(choices=[('A', 'Active'), ('SUSP', 'Suspended'), ('DEL', 'Deleted'), ('PRE', 'Pré-inscrit')], default='SUSP', max_length=10),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='professionnel/professionnel_logos/'),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='numero_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DZ', unique=True),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='theme_couleur',
            field=models.CharField(blank=True, default='#FF6B00', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='utilisateur',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionnel_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
