# Generated by Django 5.2 on 2026-08-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminToorrii', '0004_add_pre_inscrit_nullable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionnels', to='adminToorrii.categorie'),
        ),
    ]
