# Generated by Django 5.2 on 2026-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminToorrii', '0005_add_specialite_to_professionnel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professionnel',
            index=models.Index(fields=['etat_compte'], name='adminToorri_etat_co_d6852c_idx'),
        ),
        migrations.AddIndex(
            model_name='professionnellead',
            index=models.Index(fields=['wilaya'], name='adminToorri_wilaya_93f396_idx'),
        ),
        migrations.AddIndex(
            model_name='professionnellead',
            index=models.Index(fields=['statut'], name='adminToorri_statut_b28d44_idx'),
        ),
        migrations.AddIndex(
            model_name='professionnellead',
            index=models.Index(fields=['wilaya', 'statut'], name='adminToorri_wilaya_a0df6f_idx'),
        ),
    ]
