from .afficher_file_dattente_service_jour_view import AfficherFileDattenteView
from .afficher_file_dattente_detail_view import AfficherFileDattenteDetailView
from .ajouter_client_file_dattente_view import AjouterClientFileAttenteView
from .modifier_position_client_view import ModifierPositionClientFileView
from .supprimer_client_file_dattente_view import SupprimerClientFileAttenteView
from .terminer_client_file_dattente_view import TerminerClientFileAttenteView