from .ajouter_rdv_view import AjouterRdvView
from .modifier_rdv_view import ModifierRdvView
from .supprimer_rdv_view import SupprimerRdvView
from .marquer_terminer_rdv_view import MarquerTerminerRdvProView
from .marquer_absent_rdv_view import MarquerAbsentRdvProView
from .valider_rdv_view import ValiderRdvView
from .annuler_rdv_view import AnnulerRdvView
from .afficher_detail_rdv_view import AfficherDetailRdvView
from .afficher_rdv_view import ListRdvProView
from .afficher_rdv_par_service_view import ListRdvParServiceProView

